# Generated by Django 3.2.2 on 2021-08-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Self_create_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_img', models.ImageField(upload_to='shop/')),
                ('shop_name', models.CharField(max_length=15, unique=True)),
                ('shop_cash', models.IntegerField(default=0)),
            ],
        ),
    ]
