# Generated by Django 3.2.2 on 2021-08-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_create_shop',
            name='shop_img',
            field=models.ImageField(null=True, upload_to='shop/'),
        ),
    ]
