# Generated by Django 3.2.2 on 2021-08-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Self_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_name', models.CharField(default=False, max_length=15, unique=True, verbose_name='아이디')),
                ('self_password', models.CharField(default=False, max_length=15, verbose_name='비밀번호')),
                ('self_nickname', models.CharField(default=False, max_length=15, unique=True, verbose_name='닉네임')),
            ],
        ),
    ]
