# Generated by Django 3.2.2 on 2021-08-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_user',
            name='self_name',
            field=models.CharField(max_length=15, unique=True, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='self_user',
            name='self_nickname',
            field=models.CharField(max_length=15, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='self_user',
            name='self_password',
            field=models.CharField(max_length=15, verbose_name='비밀번호'),
        ),
    ]
