# Generated by Django 3.2.2 on 2021-08-14 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes_assemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes_option_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes_option_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_size', models.CharField(max_length=30)),
                ('clothes_option_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_option_parent', to='shop_divisionapp.clothes_option_title')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes_choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_choice_size', models.CharField(max_length=30)),
                ('clothes_choice_color', models.CharField(max_length=30)),
                ('clothes_choice_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_choice_title', to='shop_divisionapp.clothes_assemble')),
            ],
        ),
    ]
