# Generated by Django 3.2.2 on 2021-08-16 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
        ('shop_divisionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes_option_order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_order_img', models.ImageField(null=True, upload_to='order/')),
                ('clothes_order_number', models.IntegerField(default=1)),
                ('clothes_option_order_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_option_order_color', to='shop_divisionapp.clothes_option_color')),
                ('clothes_option_order_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_option_order_size', to='shop_divisionapp.clothes_option_size')),
                ('clothes_order_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_order_pk', to='accountapp.self_user')),
            ],
        ),
    ]
