# Generated by Django 3.2.2 on 2021-08-14 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_divisionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes_option_detail_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_option_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_option_detail', to='shop_divisionapp.clothes_option_size')),
            ],
        ),
    ]
