# Generated by Django 3.2.2 on 2021-08-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_divisionapp', '0002_clothes_option_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes_option_order_detail',
            name='clothes_option_order_color',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='clothes_option_order_detail',
            name='clothes_option_order_size',
            field=models.CharField(max_length=15),
        ),
    ]
